### ISSUE TITLE
iOS11 install failure

### ISSUE THREAD

**Issue by welkiner** [appknox/isign#14]
![default](https://user-images.githubusercontent.com/5791830/36728244-0e501e46-1bfb-11e8-9f93-a9263059baa8.png)

but success in iOS10，just the same ipa，it confused me

**Comment by cosmosgenius** [comment]
How are you installing the app?

**Comment by welkiner** [comment]
@cosmosgenius use the iFunbox, and use the enterprise certificate for signing an really simple ipa,
here is the verbose logs:

	Signing with apple_cert: /Users/tl/isign/isign/apple_credentials/applecerts.pem
	Signing with key: /Users/tl/.isign/key.pem
	Signing with certificate: /Users/tl/.isign/certificate.pem
	Signing with provisioning_profile: /Users/tl/.isign/isign.mobileprovision
	got executable /usr/bin/zip for zip
	got executable /usr/bin/unzip for unzip
	precheck
	path: /Users/tl/Desktop/TEST1/TEST.ipa
	extension match
	extension match: .ipa
	this is an archive, and a zipfile
	found one app
	is_native: True
	found one app
	File /Users/tl/Desktop/TEST1/TEST.ipa matched as IpaArchive
	Missing/invalid CFBundleSupportedPlatforms value in /var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69/Payload/TEST.app/Base.lproj/LaunchScreen.storyboardc/Info.plist
	Missing/invalid CFBundleSupportedPlatforms value in /var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69/Payload/TEST.app/Base.lproj/Main.storyboardc/Info.plist
	wrote Entitlements to /var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69/Payload/TEST.app/Entitlements.plist
	working on /var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69/Payload/TEST.app/TEST
	found fat binary
	found fat slice: cputype 12, cpusubtype 9
	slice 0: arch offset: 16384, size: 61568
	found fat slice: cputype 16777228, cpusubtype 0
	slice 1: arch offset: 81920, size: 61648
	using entitlements at path: /var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69/Payload/TEST.app/Entitlements.plist
	in length: 452, out length: 4381
	new codesig len is: 6243
	offset: 50624, write offset: 67008, new_codesig_data len: 10944
	using entitlements at path: /var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69/Payload/TEST.app/Entitlements.plist
	in length: 452, out length: 4381
	new codesig len is: 6243
	offset: 50704, write offset: 132624, new_codesig_data len: 10944
	Resigned bundle at </var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69/Payload/TEST.app>
	got executable /usr/bin/zip for zip
	archived IpaArchive to /Users/tl/Desktop/TEST1/1.ipa
	removing ua: /var/folders/pb/0wj15cn11xn7fyzc7rk4kkcm0000gn/T/isign-43x75k69

**Comment by rib** [comment]
I'm also not currently able to install a re-signed .ipa on an iOS 11 device:

```
$ ideviceinstaller -i ./Test-signed.ipa
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/Test.app/SC_Info/Test.sinf in archive!
Copying './Test-signed.ipa' to device... DONE.
Installing 'com.impossible.glimpse.Test'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)
Install: InstallingEmbeddedProfile (30%)
Install: VerifyingApplication (40%)
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008017: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.2DcJ5l/extracted/Payload/Test.app : 0xe8008017 (A signed resource has been added, modified, or deleted.)
```
I'm currently trying to test re-signing a really minimal .ipa (a blank test projected created with xcode, that just shows a white screen when running) and re-signing with the same key/certificate as the original ipa (so I guess they could theoretically end up being identical if the signing was perfectly compatible with what xcode does).

Here is a diff of the CodeResources between my working and non-working (re-signed) package:
```diff
--- PayloadOK/Test.app/_CodeSignature/CodeResources	2018-03-14 01:30:21.000000000 +0000
+++ Payload/Test.app/_CodeSignature/CodeResources	2018-03-14 01:38:49.000000000 +0000
@@ -28,6 +28,10 @@
 		<data>
 		KnSeyajE3Ehr6a9E7S22/7P0iGA=
 		</data>
+		<key>Entitlements.plist</key>
+		<data>
+		AEOhFbrP5CkJ5F8Hx9qKySbTwVo=
+		</data>
 		<key>Info.plist</key>
 		<data>
 		/LeHA5BhKiGOjxLgLKdeUfIGDnA=
@@ -113,6 +117,39 @@
 			P8UMZjN5OkVoU1EPEpe8suHaQjiLXQLM4gYHYk8MBZM=
 			</data>
 		</dict>
+		<key>Entitlements.plist</key>
+		<dict>
+			<key>hash</key>
+			<data>
+			AEOhFbrP5CkJ5F8Hx9qKySbTwVo=
+			</data>
+			<key>hash2</key>
+			<data>
+			kaO6wvLaUTCZcYRe5II9IKZeAMtREcCookKZw4XGDOY=
+			</data>
+		</dict>
+		<key>Info.plist</key>
+		<dict>
+			<key>hash</key>
+			<data>
+			/LeHA5BhKiGOjxLgLKdeUfIGDnA=
+			</data>
+			<key>hash2</key>
+			<data>
+			6NqYJIQopOSA/4Mefgp7KTS0rOveXQPp2lxZNJxn1/s=
+			</data>
+		</dict>
+		<key>PkgInfo</key>
+		<dict>
+			<key>hash</key>
+			<data>
+			n57qDP4tZfLD1rCS43W0B4LQjzE=
+			</data>
+			<key>hash2</key>
+			<data>
+			glAhkclISwTWhTdPmHmgBmBpxJuKyuegSwHTjQfo7KA=
+			</data>
+		</dict>
 		<key>archived-expanded-entitlements.xcent</key>
 		<dict>
 			<key>hash</key>
@@ -145,19 +182,19 @@
 			<key>optional</key>
 			<true/>
 			<key>weight</key>
-			<real>1000</real>
+			<real>1000.0</real>
 		</dict>
 		<key>^.*\.lproj/locversion.plist$</key>
 		<dict>
 			<key>omit</key>
 			<true/>
 			<key>weight</key>
-			<real>1100</real>
+			<real>1100.0</real>
 		</dict>
 		<key>^Base\.lproj/</key>
 		<dict>
 			<key>weight</key>
-			<real>1010</real>
+			<real>1010.0</real>
 		</dict>
 		<key>^version.plist$</key>
 		<true/>
@@ -167,26 +204,26 @@
 		<key>.*\.dSYM($|/)</key>
 		<dict>
 			<key>weight</key>
-			<real>11</real>
+			<real>11.0</real>
 		</dict>
 		<key>^</key>
 		<dict>
 			<key>weight</key>
-			<real>20</real>
+			<real>20.0</real>
 		</dict>
 		<key>^(.*/)?\.DS_Store$</key>
 		<dict>
 			<key>omit</key>
 			<true/>
 			<key>weight</key>
-			<real>2000</real>
+			<real>2000.0</real>
 		</dict>
 		<key>^(Frameworks|SharedFrameworks|PlugIns|Plug-ins|XPCServices|Helpers|MacOS|Library/(Automator|Spotlight|LoginItems))/</key>
 		<dict>
 			<key>nested</key>
 			<true/>
 			<key>weight</key>
-			<real>10</real>
+			<real>10.0</real>
 		</dict>
 		<key>^.*</key>
 		<true/>
@@ -195,50 +232,50 @@
 			<key>optional</key>
 			<true/>
 			<key>weight</key>
-			<real>1000</real>
+			<real>1000.0</real>
 		</dict>
 		<key>^.*\.lproj/locversion.plist$</key>
 		<dict>
 			<key>omit</key>
 			<true/>
 			<key>weight</key>
-			<real>1100</real>
+			<real>1100.0</real>
 		</dict>
 		<key>^Base\.lproj/</key>
 		<dict>
 			<key>weight</key>
-			<real>1010</real>
+			<real>1010.0</real>
 		</dict>
 		<key>^Info\.plist$</key>
 		<dict>
 			<key>omit</key>
 			<true/>
 			<key>weight</key>
-			<real>20</real>
+			<real>20.0</real>
 		</dict>
 		<key>^PkgInfo$</key>
 		<dict>
 			<key>omit</key>
 			<true/>
 			<key>weight</key>
-			<real>20</real>
+			<real>20.0</real>
 		</dict>
 		<key>^[^/]+$</key>
 		<dict>
 			<key>nested</key>
 			<true/>
 			<key>weight</key>
-			<real>10</real>
+			<real>10.0</real>
 		</dict>
 		<key>^embedded\.provisionprofile$</key>
 		<dict>
 			<key>weight</key>
-			<real>20</real>
+			<real>20.0</real>
 		</dict>
 		<key>^version\.plist$</key>
 		<dict>
 			<key>weight</key>
-			<real>20</real>
+			<real>20.0</real>
 		</dict>
 	</dict>
 </dict>
```
I see that there's an extra Entitlements.plist file in the new package and then besides the above CodeResources differences the remaining difference is with the `Test` app binary. (while I'm not familiar with how the signing is done I haven't looked at comparing the binaries yet)

**Comment by rib** [comment]
Poking around some more, if I unpack my good and bad .ipa files on OSX and run `codesign --verify -vvv` I can see that the original one verifies ok as expected and then the second one seems to fail somehow due to the Info.plist and PkgInfo files:

Original package from Xcode:
```
$ codesign --verify -vvv PayloadOK/Test.app/Test 
PayloadOK/Test.app/Test: valid on disk
PayloadOK/Test.app/Test: satisfies its Designated Requirement
```

Re-signed package (with same key/certificate):
```
$ codesign --verify -vvv Payload/Test.app/Test 
Payload/Test.app/Test: a sealed resource is missing or invalid
file missing: /Users/bob/Downloads/test_ipa/Payload/Test.app/PkgInfo
file missing: /Users/bob/Downloads/test_ipa/Payload/Test.app/Info.plist
```
Note those two files are actually within both packages and identical. The most obvious difference seems to be the extra entries for those files in the CodeResources file of the re-signed package.

**Comment by rib** [comment]
For a bit more data I ran `codesign -d --verbose=10` for both packages and here's a diff of the output:
```diff
--- codesignOK.txt	2018-03-14 11:39:53.000000000 +0000
+++ codesign.txt	2018-03-14 11:40:02.000000000 +0000
@@ -1,4 +1,4 @@
-Executable=/Users/bob/Downloads/test_ipa/PayloadOK/Test.app/Test
+Executable=/Users/bob/Downloads/test_ipa/Payload/Test.app/Test
 Identifier=<removed/>
 Format=app bundle with Mach-O universal (armv7 arm64)
 CodeDirectory v=20200 size=667 flags=0x0(none) hashes=13+5 location=embedded
@@ -6,13 +6,13 @@
 OSSDKVersion=721408
 OSVersionMin=655360
 Hash type=sha256 size=32
-CandidateCDHash sha1=f5c20d22a84ced1341022dcbad19c9d47ca77618
-CandidateCDHash sha256=06f5869d68b4321df5745a13ba2b58bf83391a01
+CandidateCDHash sha1=4c830973cff8c5d96db89481da0e2934983d168d
+CandidateCDHash sha256=5a9736a875885d37031b5d8b1be9aeef438bd3f4
 Hash choices=sha1,sha256
 Page size=4096
-    -5=c88e0e8da4c7685e8a114b2bb9cd9f0b34f551e822cbb0678e3f77234b518118
+    -5=94eab9d4cee0615e389542cc1ba51f68c36c67836949d22306160be451eb4ef1
     -4=0000000000000000000000000000000000000000000000000000000000000000
-    -3=73dfaf4f097ad4b30f91476be390daa6f179657dd5b3978fc854e2b0619f7793
+    -3=9bf07ef89066821e9ad404d5a235b685fa471de321db4120aa92419dd8c98422
     -2=6aa29b2867b36a8935c691a8dcf700fd6c1a38b068961a75733327cafd0745ed
     -1=e8da98248428a4e480ff831e7e0a7b2934b4acebde5d03e9da5c59349c67d7fb
      0=ce03c00377afdcceb0b9c822b2a7c476bb5b74d61226dd8dd9bc54c9109e4ed1
@@ -28,13 +28,13 @@
     10=ad7facb2586fc6e966c004d7d1d16b024f5805ff7cb47c7a85dabd8b48892ca7
     11=ad7facb2586fc6e966c004d7d1d16b024f5805ff7cb47c7a85dabd8b48892ca7
     12=0ade3c233a8870e1b8a6ce093b732df19856d96baa1a3ce8317be2dac03bd129
-CDHash=06f5869d68b4321df5745a13ba2b58bf83391a01
-Signature size=4711
+CDHash=5a9736a875885d37031b5d8b1be9aeef438bd3f4
+Signature size=4332
 Authority=iPhone Developer: <removed/>
 Authority=Apple Worldwide Developer Relations Certification Authority
 Authority=Apple Root CA
-Signed Time=14 Mar 2018 at 01:30:21
+Signed Time=14 Mar 2018 at 02:11:51
 Info.plist entries=27
 TeamIdentifier=<removed/>
-Sealed Resources version=2 rules=13 files=8
+Sealed Resources version=2 rules=13 files=11
 Internal requirements count=1 size=188
```

**Comment by rib** [comment]
Ok, I seem to have at least successfully re-signed my simple test package with these experimental changes: https://github.com/rib/isign/tree/sign-ios-11

I can look at making a pull request with some clean up, though the skip change feels a bit hacky or at least cargo-culty because all I did was try and make the result look more like the package made by iOS without really understanding why those files are skipped in the files2 section.

**Comment by subho007** [comment]
This is awesome @rib can you send a PR ? Will review it 👍

**Comment by welkiner** [comment]
@rib awesome~！

**Comment by rib** [comment]
For reference, when I subsequently looked at signing from scratch for iOS 11 it turned into a much bigger can of worms.

I opened https://github.com/appknox/isign/issues/17 with some initial problems I hit and created an experimental branch at https://github.com/rib/isign/tree/wip/rib/sign-from-scratch-for-ios11 (sorry very messy atm) but haven't quite got it working yet.

Comparing with codesign output I can see it's getting very close, but I have a feeling I might run out of steam soon so posting links in case someone else might be able to help figure out the last bits.
